print("   /\\  ")
print("  /  \\  ")
print(" /    \\  ")
print("+______+   ")
print("|      |")
print("|      |")
print("+______+   ")
print("|  TO  |")
print("|Space |")
print("+______+   ")
print("|      |")
print("|      |")
print("+______+   ")
print("   /\\  ")
print("  /  \\  ")
print(" /    \\  ")
